/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppBriefingRouteImport } from './routes/_app.briefing'
import { Route as AppCompareRouteImport } from './routes/_app.compare'
import { Route as AppDevicesRouteImport } from './routes/_app.devices'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppLedgerRouteImport } from './routes/_app.ledger'
import { Route as AppMeshRouteImport } from './routes/_app.mesh'
import { Route as AppSocRouteImport } from './routes/_app.soc'
import { Route as AppTraceRouteImport } from './routes/_app.trace'
import { Route as AppDistributeNewRouteImport } from './routes/_app.distribute.new'
import { Route as AppDistributionsIndexRouteImport } from './routes/_app.distributions.index'
import { Route as AppDistributionsDocIdRouteImport } from './routes/_app.distributions.$docId'
import { Route as AppEvidenceCaseIdRouteImport } from './routes/_app.evidence.$caseId'
import { Route as AppViewDocIdRouteImport } from './routes/_app.view.$docId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBriefingRoute = AppBriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppMeshRoute = AppMeshRouteImport.update({
  id: '/mesh',
  path: '/mesh',
  getParentRoute: () => AppRoute,
} as any)
const AppSocRoute = AppSocRouteImport.update({
  id: '/soc',
  path: '/soc',
  getParentRoute: () => AppRoute,
} as any)
const AppTraceRoute = AppTraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => AppRoute,
} as any)
const AppDistributeNewRoute = AppDistributeNewRouteImport.update({
  id: '/distribute/new',
  path: '/distribute/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDistributionsIndexRoute = AppDistributionsIndexRouteImport.update({
  id: '/distributions/',
  path: '/distributions/',
  getParentRoute: () => AppRoute,
} as any)
const AppDistributionsDocIdRoute = AppDistributionsDocIdRouteImport.update({
  id: '/distributions/$docId',
  path: '/distributions/$docId',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceCaseIdRoute = AppEvidenceCaseIdRouteImport.update({
  id: '/evidence/$caseId',
  path: '/evidence/$caseId',
  getParentRoute: () => AppRoute,
} as any)
const AppViewDocIdRoute = AppViewDocIdRouteImport.update({
  id: '/view/$docId',
  path: '/view/$docId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/briefing': typeof AppBriefingRoute
  '/compare': typeof AppCompareRoute
  '/devices': typeof AppDevicesRoute
  '/inbox': typeof AppInboxRoute
  '/ledger': typeof AppLedgerRoute
  '/mesh': typeof AppMeshRoute
  '/soc': typeof AppSocRoute
  '/trace': typeof AppTraceRoute
  '/distribute/new': typeof AppDistributeNewRoute
  '/distributions/$docId': typeof AppDistributionsDocIdRoute
  '/evidence/$caseId': typeof AppEvidenceCaseIdRoute
  '/view/$docId': typeof AppViewDocIdRoute
  '/distributions/': typeof AppDistributionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefing': typeof AppBriefingRoute
  '/compare': typeof AppCompareRoute
  '/devices': typeof AppDevicesRoute
  '/inbox': typeof AppInboxRoute
  '/ledger': typeof AppLedgerRoute
  '/mesh': typeof AppMeshRoute
  '/soc': typeof AppSocRoute
  '/trace': typeof AppTraceRoute
  '/distribute/new': typeof AppDistributeNewRoute
  '/distributions/$docId': typeof AppDistributionsDocIdRoute
  '/evidence/$caseId': typeof AppEvidenceCaseIdRoute
  '/view/$docId': typeof AppViewDocIdRoute
  '/distributions': typeof AppDistributionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/briefing': typeof AppBriefingRoute
  '/_app/compare': typeof AppCompareRoute
  '/_app/devices': typeof AppDevicesRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/ledger': typeof AppLedgerRoute
  '/_app/mesh': typeof AppMeshRoute
  '/_app/soc': typeof AppSocRoute
  '/_app/trace': typeof AppTraceRoute
  '/_app/distribute/new': typeof AppDistributeNewRoute
  '/_app/distributions/$docId': typeof AppDistributionsDocIdRoute
  '/_app/evidence/$caseId': typeof AppEvidenceCaseIdRoute
  '/_app/view/$docId': typeof AppViewDocIdRoute
  '/_app/distributions/': typeof AppDistributionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/briefing'
    | '/compare'
    | '/devices'
    | '/inbox'
    | '/ledger'
    | '/mesh'
    | '/soc'
    | '/trace'
    | '/distribute/new'
    | '/distributions/$docId'
    | '/evidence/$caseId'
    | '/view/$docId'
    | '/distributions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/briefing'
    | '/compare'
    | '/devices'
    | '/inbox'
    | '/ledger'
    | '/mesh'
    | '/soc'
    | '/trace'
    | '/distribute/new'
    | '/distributions/$docId'
    | '/evidence/$caseId'
    | '/view/$docId'
    | '/distributions'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/briefing'
    | '/_app/compare'
    | '/_app/devices'
    | '/_app/inbox'
    | '/_app/ledger'
    | '/_app/mesh'
    | '/_app/soc'
    | '/_app/trace'
    | '/_app/distribute/new'
    | '/_app/distributions/$docId'
    | '/_app/evidence/$caseId'
    | '/_app/view/$docId'
    | '/_app/distributions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/briefing': {
      id: '/_app/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof AppBriefingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compare': {
      id: '/_app/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ledger': {
      id: '/_app/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mesh': {
      id: '/_app/mesh'
      path: '/mesh'
      fullPath: '/mesh'
      preLoaderRoute: typeof AppMeshRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/soc': {
      id: '/_app/soc'
      path: '/soc'
      fullPath: '/soc'
      preLoaderRoute: typeof AppSocRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trace': {
      id: '/_app/trace'
      path: '/trace'
      fullPath: '/trace'
      preLoaderRoute: typeof AppTraceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/distribute/new': {
      id: '/_app/distribute/new'
      path: '/distribute/new'
      fullPath: '/distribute/new'
      preLoaderRoute: typeof AppDistributeNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/distributions/': {
      id: '/_app/distributions/'
      path: '/distributions'
      fullPath: '/distributions/'
      preLoaderRoute: typeof AppDistributionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/distributions/$docId': {
      id: '/_app/distributions/$docId'
      path: '/distributions/$docId'
      fullPath: '/distributions/$docId'
      preLoaderRoute: typeof AppDistributionsDocIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evidence/$caseId': {
      id: '/_app/evidence/$caseId'
      path: '/evidence/$caseId'
      fullPath: '/evidence/$caseId'
      preLoaderRoute: typeof AppEvidenceCaseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/view/$docId': {
      id: '/_app/view/$docId'
      path: '/view/$docId'
      fullPath: '/view/$docId'
      preLoaderRoute: typeof AppViewDocIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBriefingRoute: typeof AppBriefingRoute
  AppCompareRoute: typeof AppCompareRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppInboxRoute: typeof AppInboxRoute
  AppLedgerRoute: typeof AppLedgerRoute
  AppMeshRoute: typeof AppMeshRoute
  AppSocRoute: typeof AppSocRoute
  AppTraceRoute: typeof AppTraceRoute
  AppDistributeNewRoute: typeof AppDistributeNewRoute
  AppDistributionsDocIdRoute: typeof AppDistributionsDocIdRoute
  AppEvidenceCaseIdRoute: typeof AppEvidenceCaseIdRoute
  AppViewDocIdRoute: typeof AppViewDocIdRoute
  AppDistributionsIndexRoute: typeof AppDistributionsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBriefingRoute: AppBriefingRoute,
  AppCompareRoute: AppCompareRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppInboxRoute: AppInboxRoute,
  AppLedgerRoute: AppLedgerRoute,
  AppMeshRoute: AppMeshRoute,
  AppSocRoute: AppSocRoute,
  AppTraceRoute: AppTraceRoute,
  AppDistributeNewRoute: AppDistributeNewRoute,
  AppDistributionsDocIdRoute: AppDistributionsDocIdRoute,
  AppEvidenceCaseIdRoute: AppEvidenceCaseIdRoute,
  AppViewDocIdRoute: AppViewDocIdRoute,
  AppDistributionsIndexRoute: AppDistributionsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
